name=TrTmonitor
version=3
author=TrTHUC
maintainer=Arduino <info@arduino.cc>
sentence=Arduino boards. 
paragraph=This library supports learning Microcontrollers.
category=Device Control.
url=http://www.arduino.cc/en/Reference/TrTmonitor
architectures=*
